# Generated by Django 3.1.1 on 2020-09-14 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyConsumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_servings', models.PositiveSmallIntegerField(verbose_name=0)),
            ],
            options={
                'verbose_name_plural': 'daily_consumptions',
            },
        ),
        migrations.CreateModel(
            name='WeeklyConsumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_consumed_this_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meat_consumption.dailyconsumption')),
            ],
            options={
                'verbose_name_plural': 'weekly_consumptions',
            },
        ),
    ]
