# Generated by Django 3.1.1 on 2020-09-15 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyConsumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_servings', models.PositiveSmallIntegerField(verbose_name=0)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'daily_consumptions',
            },
        ),
        migrations.CreateModel(
            name='WeeklyConsumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_total_consumption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meat_consumption.dailyconsumption')),
            ],
            options={
                'verbose_name_plural': 'weekly_consumptions',
            },
        ),
    ]
