# Generated by Django 3.1.1 on 2020-09-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_consumption', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyconsumption',
            name='consumed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyconsumption',
            name='day_consumed',
            field=models.DateField(default='2020-09-14'),
        ),
    ]
