# Generated by Django 3.1.1 on 2020-09-16 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meat_consumption', '0002_auto_20200915_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyconsumption',
            name='weekly_total_consumption',
        ),
        migrations.AddField(
            model_name='dailyconsumption',
            name='weekly_consumption',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meat_consumption.weeklyconsumption'),
            preserve_default=False,
        ),
    ]
