# Generated by Django 3.1.1 on 2020-09-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_consumption', '0003_auto_20200916_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyconsumption',
            name='week_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
