# Generated by Django 3.1.1 on 2020-09-16 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meat_consumption', '0004_weeklyconsumption_week_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyconsumption',
            name='owner',
        ),
        migrations.AddField(
            model_name='weeklyconsumption',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
