# Generated by Django 3.1.1 on 2020-09-17 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meat_consumption', '0005_auto_20200916_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyconsumption',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weeklyconsumption',
            name='week_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
