# Generated by Django 3.1.1 on 2020-09-19 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meat_consumption', '0006_auto_20200917_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyconsumption',
            name='day_consumed',
        ),
    ]
