# Generated by Django 3.1.1 on 2020-09-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_consumption', '0008_auto_20200919_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyconsumption',
            name='day_consumed',
            field=models.DateField(),
        ),
    ]
