# Generated by Django 3.1.1 on 2020-09-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_consumption', '0009_auto_20200919_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyconsumption',
            name='day_consumed',
            field=models.CharField(max_length=50),
        ),
    ]
