# Generated by Django 3.1.1 on 2020-09-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_consumption', '0011_auto_20200920_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyconsumption',
            name='day_consumed',
            field=models.CharField(max_length=50),
        ),
    ]
