# Generated by Django 3.1.1 on 2020-09-20 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meat_consumption', '0012_auto_20200920_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyconsumption',
            name='weekly_consumption',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='meat_consumption.weeklyconsumption'),
        ),
    ]
